---
info:
  component: Default Single Swagger Document Server for MicroService

spring:
  profiles: default
  application:
    name: swagger-service

eureka:
  client:
    register-with-eureka: true
    fetch-regsitery: true

server:
  port: 8014

documentation:
  baseurl: http://localhost
  swagger:
    services:
      -
        name: Admin
        url: http://localhost:8083/v2/api-docs?group=admin
        version: 2.0
      -
        name: Borrower
        url: http://localhost:8081/v2/api-docs?group=borrower
        version: 2.0
      -
        name: Librarian
        url: http://localhost:8082/v2/api-docs?group=librarian
        version: 2.0
